config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :rides
  end
 
  get "/signup" => "users#new"
  post "/users" => "users#create"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  get "/rides" => "rides#rides_index"
  get "/rides/:id/request" => "rides#request_ride"
  get "/rides/:id/offer" => "rides#offer_to_request"

  get "/offer_ride" => "rides#offer_form", as: "show_offer_form"
  post "/offer_ride" => "rides#create_offer", as: "create_offer"

  get "create_request" => "rides#request_form"
  post "create_request" => "rides#create_request"

  get "/requests/:id/accept" => "requests#accept"
  get "/requests/:id/decline" => "requests#decline"
  get "/requests" => "requests#index"
  
  root "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :ride
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :user
  has_many :requests
  belongs_to :driver, :class_name => "User", optional: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, uniqueness: true
    has_secure_password
    has_many :rides
    has_many :requests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
    def decline
        request = Request.find(params[:id])
        request.accepted = false
        request.save
        flash[:success] = "Request rejected"
        redirect_to user_rides_path(user_id: session[:user_id])
    end

    def accept
        request = Request.find(params[:id])
        ride = request.ride
        if ride.capacity <= 0
            flash[:warning] = "Unable to accept capacity reached"
            redirect_to user_rides_path(session[:user_id])
            return
        end
        
        request.accepted = true
        ride.capacity -= 1
        ride.save
        request.save
        flash[:success] = "Request accepted"
        redirect_to user_rides_path(user_id: session[:user_id])
    end

    def index
        user = User.find(session[:user_id])
        @requests = user.requests 
    end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
    before_action :set_ride,only: [:request_ride, :offer_to_request ]

    def new
        @ride = Ride.new
    end

    def create_request
       ride = user.rides.create(ride_params)
       request = Request.new(user: user, ride: ride)
       request.save
       redirect_to '/rides'
    end

    def offer_to_request 
        @ride.driver_id = user.id
        @ride.save
        flash[:success] = "ride offered succesfully" 
        redirect_to "/rides" 
    end

    def create_offer
        puts ride_params.inspect
        ride_params["driver_id"] = user.id
        ride = user.rides.create(ride_params)
        puts ride.errors.inspect
        redirect_to "/rides"
    end

    def request_form
        @ride = Ride.new
    end

    def offer_form
        @ride = Ride.new
    end

    def rides_index
        @rides  = Ride.all
    end

    def index 
        @rides = user.rides
    end

    def request_ride
        @ride.requests.create(user_id: user.id)
        flash[:success] = "request succesful" 
        redirect_to "/rides"
    end


    private
        def set_ride
            @ride = Ride.find(params[:id])
        end

        def ride_params
            params.require(:ride).permit!
        end

        def user
            User.find(session[:user_id])
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        user = User.find_by_email(user_params[:email])
        if user && user.authenticate(user_params[:password])
            flash[:success] = "login successful"
            session[:user_id] = user.id 
            redirect_to "/"
        else
            flash[:warning] = "Invalid email or password"
            redirect_to "/login"
        end
    
    end

    def destroy
        session.clear()
        redirect_to "/"
    end

    private 
     def user_params
        params.require(:user).permit(:email, :password)
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user,  only: [:show, :update, :edit]
    def new
        @user = User.new
    end

    def create
        user = User.new(user_params)
        if user.save
            flash[:success] = "succesfully created the user #{user.name}"
            redirect_to "/login"
        else
            flash[:warning] = "failure in registering. Confirm your information"
            redirect_to "/signup"
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
    end
    private 
        def set_user
            @user = User.find(params[:id])
        end
        def user_params
            params.require(:user).permit(:name, :email, :phone, :password, :password_confirmation)
        end 
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        if session[:user_id] 
            @current_user ||= User.find(session[:user_id]) 
        else
            @current_user =  nil
        end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
    def my_requests
        @my_requests = Request.where(user_id: session[:user_id]).pluck(:ride_id)
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
 <div class="container">
  <div class="container text-center">
    <div class="title">
    <h1>Welcome</h1>
    </div>
    <p>Welcome to RideShare your number one tranport solution.  
    You will be able to offer and book rides from your collagues.<br>
    Get the best experience to your location by booking offered rides</p>
    <% if not current_user%>
    <a href="/login" class="btn btn-secondary">Login</a>
    <a href="users/new" class="btn btn-secondary">Signup</a>
    <%end%>
  </div>
  <br>
  <br>
  <hr>
  <div class="row">
    <div class="col-sm-6">
        <div class="card" style = "border:none">
        <div class="card-body">
            <h5 class="card-title">Request ride</h5>
            <p class="card-text">With <strong >RideShare</strong> you are able to request rides from your collagues headed
            in the same direction as yourself</p>
            <%if current_user%>
            <a href=<%= create_request_path %> class="btn btn-primary">Request a ride</a>
            <%end%>
        </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card" style = "border:none">
        <div class="card-body">
            <h5 class="card-title">Offer to share a ride</h5>
            <p class="card-text"> Headed somewhere with your car and need of compnany or just want to helpp a collague out. Offer them a ride.</p>
            <%if current_user%>
            <a href= <%= show_offer_form_path %> class="btn btn-primary">Offer a ride</a>
            <%end%>
        </div>
        </div>
    </div>
    </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RideShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Ride<i>Share</i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only"></span></a>
      </li>
      <%if current_user %>
      <li class="nav-item">
        <%= link_to "All Rides", "/rides", class: "nav-link "%>
      </li>
      <li class="nav-item">
        <%= link_to "Profile", user_path(current_user), class: "nav-link "%>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle mr-2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href=<%= show_offer_form_path %>>Offer ride</a>
          <a class="dropdown-item" href=<%= user_rides_path(current_user)%>>My rides</a>
           <a class="dropdown-item" href= <%= create_request_path %>> Request ride</a>
           <a class="dropdown-item" href="/requests">My requests</a>
          <div class="dropdown-divider"></div>

          <a class="dropdown-item " href="/logout" tabindex="-1" >Logout</a>
  
        </div>
      </li>
      
      <%else%>
      <li class="nav-item active">
        <a class="nav-link" href="/signup">Signup <span class="sr-only"></span></a>
      </li><li class="nav-item active">
        <a class="nav-link" href="/login">Login <span class="sr-only"></span></a>
      </li>
      <%end%>
    </ul>
  </div>
</nav>
  <div class="container spaced">
  <div class="container">
    <% flash.each do |name, message| %>
      <div class="alert alert-<%=name%> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong><%= name.upcase %></strong> <%= message%>
     </div>
    <%end%>
  </div>
    <%= yield %>
  </div>
  
  </body>
</html>

app/views/requests/index.html.erb
<h2>My Requests</h2>
<% @requests.each do |request|%>
 <% ride = request.ride %>
    <div class="card">

     <div class="card-header">
        <span><strong>Offer by</strong> <%= ride.user.name.capitalize%><span>
    </div>
 <div class="card-body">

    <div class="row">
        <div class="col-sm-6">
            <p>Origin</p>
        </div>
        <div class="col-sm-6">
        <p><%= ride.origin %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <p>destination</p>
        </div>
        <div class="col-sm-6">
        <p><%= ride.destination %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <p>Take off</p>
        </div>
        <div class="col-sm-6">
        <p><%= ride.time %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <p>Capacity</p>
        </div>
        <div class="col-sm-6">
        <p><%= ride.capacity %></p>
        </div>
    </div>
 </div>
 <div class="card-footer">
        <div class="row">
        <div class="col-sm-6" style="display:inline;">
            <strong>Status</strong>
        </div>
        <div class="col-sm-6 ">
        <%= "Pending" if request.accepted == nil %>
        <%= "Accepted" if request.accepted  %>
        <%= "Rejected" if request.accepted == false %>
        </div>
        </div>
    </div>
 </div>
 <br>
<%end%>

app/views/rides/_form.html.erb
<%= form_for ride, url:{action: action} do |form| %>
<p> 
<%=  form.label :origin %>
<%= form.text_field :origin, class: :"form-control"%>
</p>
<p>
<%=  form.label :destination %>
<%= form.text_field :destination, class: :"form-control"%>
</p>
<p>
<%=  form.label :take_off %>
<%= form.text_field :time, class: :"form-control",id: "take_off" %>
<script type="text/javascript">
  const el = document.getElementById('take_off');
  flatpickr(el, {enableTime: true} );
</script>


</p>
<p>
<%=  form.label :capacity %>
<%= form.text_field :capacity, class: :"form-control" %>
</p>
<p>
<%= form.submit class: "btn btn-primary" %>
</p>

<% end %>

app/views/rides/index.html.erb
<h2>My Rides</h2>
<% @rides.each do |ride|%>
 <div class="card">
 <div class="card-body">
    <div class="row">
        <div class="col-sm-6">
            <p>Origin</p>
        </div>
        <div class="col-sm-6">
        <p><%= ride.origin %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <p>destination</p>
        </div>
        <div class="col-sm-6">
        <p><%= ride.destination %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <p>Take off</p>
        </div>
        <div class="col-sm-6">
        <p><%= ride.time %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <p>Capacity</p>
        </div>
        <div class="col-sm-6">
        <p><%= ride.capacity %></p>
        </div>
    </div>
    
    <div class="modal fade" id="modal-<%=ride.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Requests</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <% ride.requests.each do |request|%>
            <%if request.accepted == nil %>
            <div class="row" style="padding-bottom:2px;">
                <div class="col-md-6"><%= request.user.name%></div>
                 <div class="col-md-6">
                    <a href=<%="/requests/#{request.id}/accept"%> class="btn btn-primary">accept</a>
                    <a href=<%="/requests/#{request.id}/decline"%> class="btn btn-danger">reject</a>
                 </div>
                </div>
                <hr>
            <%end%>
            <%end%>
            <p> No more unreplied requests</p>
        </div>
        <div class="modal-footer" style="border-top:none;">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
        </div>
    </div>
    </div>



    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-<%=ride.id%>">
    View Requests
    </button>
 </div>
 </div>
 <br>
<%end%>
</div>

app/views/rides/offer_form.html.erb
<div class="card">
<div class="card-body">
<div class="card-title"><h2>Offer a ride</h2></div>
<%= render "form", ride: @ride, action: "create_offer" %>
<%= link_to "offer from all rides", "/rides"%>
</div>

app/views/rides/request_form.html.erb
<div class="card">
<div class="card-body">
<div class="card-title"><h2>Request a ride</h2></div>
<%= render "form", ride: @ride, action: "create_request" %>
<%= link_to "request from all rides", "/rides"%>
</div>
</div>

app/views/rides/rides_index.html.erb
<h2> All Rides</h2>
<% @rides.each do |ride|%>
 <div class="card">

     <div class="card-header">
        <span><strong><%=  ride.driver_id ? "Offer by" : "Request by"%></strong> <%= ride.user.name.capitalize%><span>
    </div>
 <div class="card-body">

    <div class="row">
        <div class="col-sm-6">
            <p>Origin</p>
        </div>
        <div class="col-sm-6">
        <p><%= ride.origin %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <p>destination</p>
        </div>
        <div class="col-sm-6">
        <p><%= ride.destination %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <p>Take off</p>
        </div>
        <div class="col-sm-6">
        <p><%= ride.time %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <p>Capacity</p>
        </div>
        <div class="col-sm-6">
        <p><%= ride.capacity %></p>
        </div>
    </div>

    <% if ride.user_id != current_user.id and ride.driver_id != nil and ride.capacity > 0%>
    <a href="/rides/<%= ride.id %>/request" class="btn btn-primary  <%= "disabled" if my_requests.include?(ride.id)  %>">Request</a>
    <%elsif ride.user_id != current_user.id and ride.driver_id == nil %>
        <a href="/rides/<%= ride.id %>/offer" class="btn btn-primary ">Accept request</a>
    <%end%>

 </div>
 </div>
 <br>
<%end%>

app/views/users/_form.html.erb
<%= form_for(user) do |form| %>

<p> 
<%=  form.label :username %>
<%= form.text_field :name, class: :"form-control"%>
</p>
<p>
<%=  form.label :email %>
<%= form.email_field :email, class: :"form-control"%>
</p>
<p>
<%=  form.label :phone %>
<%= form.text_field :phone, class: :"form-control" %>
</p>
<p>
<%=  form.label :password %>
<%= form.password_field :password, class: :"form-control" %>
</p>
<p>
<%=  form.label :password_confirmation %>
<%= form.password_field :password_confirmation, class: :"form-control"%>
</p>
<p>
<%= form.submit class: "btn btn-primary" %>
</p>
</div>

<% end %>

app/views/users/edit.html.erb
<div class="card">
<div class="card-body">
<div class="card-title"><h2>Update Profile</h2></div>
<%= render "form", user: @user%>
</div>
</div>
</div>

app/views/users/new.html.erb
<div class="card">
<div class="card-body">
<div class="card-title"><h2>Signup</h2></div>
<%= render "form", user: @user%>
</div>
</div>

app/views/users/show.html.erb
<div class="card" >
<div class="card-body">
<div calss="card-title"><h2>My Profile</h2></div>
<br>
<div class="row">
    <div class="col-md-6">
    <strong>Name</strong>
    </div>
    <div class="col-md-6">
    <p><%=@user.name%></p>
    </div>

    <div class="col-md-6">
    <strong>Email</strong>
    </div>
    <div class="col-md-6">
    <p><%=@user.email%></p>
    </div>

     <div class="col-md-6">
    <strong>Phone</strong>
    </div>
    <div class="col-md-6">
    <p><%=@user.phone%></p>
    </div>
</div>

<a class="btn btn-primary" href= <%= edit_user_path(@user) %>> Edit Profile</a>
</div>
</div>